### ISSUE TITLE
Clans: Player able to be in two clans at the same time

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website-backend#134]
From the DB:

Hipposaur is a shaman in clan SuN
![shaman-sun](https://user-images.githubusercontent.com/40397054/113998737-43ab3a00-9851-11eb-91d3-a64f509abf35.PNG)

He joined clan RPTR:
![RPTR-gaming](https://user-images.githubusercontent.com/40397054/113998802-5160bf80-9851-11eb-886d-06d8a0098513.PNG)

First suspicion is that this is because he's a shaman, and it perhaps doesnt check against shamans when checking to see if you're in a clan?

**Comment by Cepheid-UK** [comment]
If anyone wants to tackle this, I think we should refactor this so that ALL people in the clan are "members" and the groups "shaman" and "chieftain" must match one of the entries in "members".

This would likely solve a number of bugs we get in clan states.

**Comment by wkozuch** [comment]
Hey! I can fix this (and the other clan open issue #158)

**Comment by Cepheid-UK** [comment]
> Hey! I can fix this (and the other clan open issue #158)
> 
> Just I have one questions here: 
> 
> 1. Is it safe to assume that a founding father of clan does not have to be a member of it? 
> 

Hey, thanks for investigating this.

If you want to figure out whats going on, I recommend you run a mongodb locally, point the `IntegrationTestBase.cs` to your local, and run the clan tests on it.

You can add a few new tests to try figure out the behaviour and narrow it down.
