### ISSUE TITLE
Code review: suspicious place in MatchesController.cs

### ISSUE THREAD

**Issue by QtRoS** [w3champions/website-backend#171]
Hi guys. 

I was reviewing project's code and found some supsicious place in [MatchesController.cs](https://github.com/w3champions/website-backend/blob/master/W3ChampionsStatisticService/Matches/MatchesController.cs):

![image](https://user-images.githubusercontent.com/1700047/166157506-2776233e-0be4-4af4-9b21-9efc0c8d72a2.png)

Seems that FFA match will never get to `PlayersObfuscator.ObfuscatePlayersForFFA`. I would rewrite it something like:

```
[HttpGet("ongoing/{playerId}")]
public async Task<IActionResult> GetOnGoingMatches(string playerId)
{
    var onGoingMatch = await _matchRepository.TryLoadOnGoingMatchForPlayer(playerId);

    if (onGoingMatch == null)
        return Ok(null);

    if (onGoingMatch.GameMode == GameMode.FFA)
        PlayersObfuscator.ObfuscatePlayersForFFA(onGoingMatch);

    return Ok(onGoingMatch);
}
```

If you don't mind I'll do PR.

**Comment by abeninski** [comment]
Hmm. Now that I think about it. Maybe someone from FFA community ask me to not return anything for FFA. We should ask FFA community again about this tbh

**Comment by amacado** [comment]
See this pull request https://github.com/w3champions/website-backend/pull/48 for a hint

**Comment by QtRoS** [comment]
@amacado if it is intended, the only good thing which can be done is removing `ObfuscatePlayersForFFA` call to remove convtoversy.

**Comment by QtRoS** [comment]
Closing since it's not an error.
