### ISSUE TITLE
"gateWay" from the api/players/global-search endpoint

### ISSUE THREAD

**Issue by 0nlyDev** [w3champions/website-backend#276]
Hi,

Can you please include the "gateWay"  (player region) in the results returned from the api/players/global-search endpoint?
I need this for the opensource [w3c discord bot](https://github.com/0nlyDev/w3c-discord-bot) i started developing recently. 
I am implementing a search which will list the players from the search results in a MenuSelect (a dropdown like object in discord messages), where users can select the player from the search results. But without having the region, users will have to provide the region themselves (which is not convenient at all). IMO, for all intents and purposes the gateWay (region) should be returned as well.

Bonus request: Include the 1vs1 mmr as well (reason is, people may be able to find the player they are searching for by the mmr), country, main race, etc.

It would be nice to update the frontend to include the region (maybe the mmr as well) on the front-end search results, but my feature request for this is purely backend.

Thank you!

**Comment by gustav87** [comment]
Nowadays there is only one gateway. The Europe gateway.

There are many endpoints that return a player mmr. Such as api/players/<battletag>/mmr-rp-timeline

Reopen if you need more assistance, or if I misunderstood the request.
