### ISSUE TITLE
Some duplicate lowercase usernames prevent the backend from returning the correct player results

### ISSUE THREAD

**Issue by 0nlyDev** [w3champions/website-backend#280]
https://website-backend.w3champions.com/api/players/global-search?search=FChampRaRa%231204&pageSize=20
does not correspond with https://www.w3champions.com/player/FChampRaRa%231204 but instead with
https://www.w3champions.com/player/fchamprara%231204

**Comment by gustav87** [comment]
Not sure if this is still relevant. Open again if you have a fresh example.
